# -*- coding: utf-8 -*-
"""Gradio_components.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZd1yuVvReAf7XYp-eB4_Upy8VNfkpI-
"""

!pip install gradio

import gradio as gr
import random

# Additional sentences to display when the button is pressed
additional_sentences = [
    [(' Emma Watson', 'PERS'), ('is', None), ('famous', None), ('for',  None),('playing',  None),('Hermione', 'PERS')],
    [('Amazon', 'ORG'), ('started', None), ('as', None), ('an', None),('online', None), ('bookstore.', None)],
    [ ('أحمد ', 'PERS'), ('هو', None), (' عالم', None), (' في', None), (' مجال', None), (' الذكاء', None), (' الاصطناعي', None)],
     [('الرياض ', 'LOC'), ('هي', None), (' مركزًا', None), (' اقتصاديًا', None), (' هامًا', None)] ]

# Custom CSS for right-to-left (RTL) text alignment
custom_css = """
#output {
    direction: rtl;  /* Right-to-left for Arabic */
    text-align: right; /* Align right for Arabic */
}
"""

# Gradio interface function to return the highlighted text
def display_highlighted_text():
    # Select a random sentence from the additional sentences
    new_data = random.choice(additional_sentences)
    return new_data

# Gradio interface to display the highlighted text
highlighted_interface = gr.Interface(
    fn=display_highlighted_text,
    inputs=None,  # No input needed, we already have the data
    outputs=gr.HighlightedText(label="Highlighted NER Results", elem_id="output"),
    title="Named Entity Recognition",  # Interface title
    description="Select a language and enter text to extract and highlight named entities.",  # Description
    css=custom_css  # Apply custom CSS for RTL
)

# Launch the Gradio interface
highlighted_interface.launch()  # Start the Gradio interface