# -*- coding: utf-8 -*-
"""text-to-text_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ddpKFTNYH3s1zqPP3vwKtQnQ7po-VcJ
"""

!pip install transformers
!pip install pandas

import pandas as pd
from transformers import pipeline

# Set display options in pandas
pd.set_option('display.max_colwidth', None)  # Show full content in cells
pd.set_option('display.width', 1000)         # Set width to prevent line breaks

# Load NER model for English and Arabic
ner_pipeline_en = pipeline('ner', grouped_entities=True)  # English model
ner_pipeline_ar = pipeline('ner', model='CAMeL-Lab/bert-base-arabic-camelbert-msa-ner', grouped_entities=True)  # Arabic model

def get_ner_pipeline(language='en'): #Return the NER model based on the specified language.
    if language == 'ar':
        return ner_pipeline_ar  # Arabic model
    return ner_pipeline_en  # English model

def entities_to_dataframe(sentences, language='en'): #Extract entities from sentences and return them as a DataFrame.
    ner_pipeline = get_ner_pipeline(language)  # Get the NER model
    all_entities = []  # List to store entities

    for sentence in sentences:
        entities = ner_pipeline(sentence)  # Process each sentence
        for entity in entities:
                all_entities.append({
                    "Entity": entity['word'],  # Extracted entity
                    "Type": entity['entity_group'],  # Type of entity
                    "Score": round(entity['score'], 2),  # Confidence score
                    "Sentence": sentence  # Original sentence
                })

    df = pd.DataFrame(all_entities)  # Convert the list to a DataFrame
    return df  # Return the DataFrame

# Input sentences for testing
english_sentences = [
    "Amazon started as an online bookstore.",
    "Hugging Face Inc. is a company based in New York City.",
    "Emma Watson is famous for playing Hermione.",
]

arabic_sentences = [
    " الرياض هي مركزًا اقتصاديًا هامًا",
    "أحمد هو عالم في مجال الذكاء الاصطناعي",
    "نورة هي مهندسة معمارية مشهورة في بلادها",
]

# Process English sentences
df_en = entities_to_dataframe(english_sentences, language='en')
print("\nEnglish NER Results:")
print(df_en)  # Print English results

# Process Arabic sentences
df_ar = entities_to_dataframe(arabic_sentences, language='ar')
print("\nArabic NER Results:")
print(df_ar, "\n")  # Print Arabic results